dist: xenial
before_install:
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
- tar zxf install-tl-unx.tar.gz
- install-tl-*/install-tl --profile=travis-ci/texlive.profile
# this is fragile; TODO figure out how to programmatically get architecture
- export PATH=$PATH:/tmp/texlive/2017/bin/x86_64-linux/
- tlmgr install texliveonfly
# dynamically grab dependencies
- texliveonfly resume.tex
script:
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume '\def\PROJECTS{}\input{resume}'
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume_noproj '\input{resume}'
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume_pub '\def\PROJECTS{}\def\PUBLIC{}\input{resume}'
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume_noproj_pub '\def\PUBLIC{}\input{resume}'
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume_full '\def\SHALEM{}\input{resume}'
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume_full_pub '\def\SHALEM{}\def\PUBLIC{}\input{resume}'
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume_monster '\def\PROJECTS{}\def\MONSTER{}\input{resume}'
- pdflatex -interaction=nonstopmode -halt-on-error -jobname=resume_dice '\def\PROJECTS{}\def\DICE{}\input{resume}'
